name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: linux package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: hvac-demo-device-linux
        path: dist/hvac-demo-device-linux
    - name: mac package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: hvac-demo-device-macos
        path: dist/hvac-demo-device-macos     
    - name: win package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: hvac-demo-device-win
        path: dist/hvac-demo-device-win.exe             
